DROP TABLE IF EXISTS manufacturer;
DROP TABLE IF EXISTS head;

CREATE TABLE manufacturer (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR
) ENGINE=InnoDB;

CREATE TABLE item (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR NOT NULL,
    
    
CREATE TABLE head (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR NOT NULL,
    